<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Validators\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Vidnova.Domain\Vidnova.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Mapster" Version="10.0.0" />
      <PackageReference Include="Mapster.DependencyInjection" Version="10.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
    </ItemGroup>

</Project>
