version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: vidnova_db
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: